### ISSUE TITLE
`no_logs` as default statically disables logging globally for any consumer

### ISSUE THREAD

**Issue by prasannavl** [ccmlm/vsdb#21]
- This pulls `vsdbsled`. That has a feature `no_logs`, which is also a part of the default set. 
- `no_logs` statically sets `log`'s MAX_LEVEL to false, all silently with no indication through cargo or anywhere else beyond the additional crates showing up in Cargo.lock files.
- This globally and "statically" sets the entire program that uses this library's logging to be off and swallowed. 
- This results in extremely hard to debug why logging output suddenly went missing and tracing this back down to this dependency. 
- This is critical bug for any downstream consumer 

Note: To make matters worse - the `vsdbsled` cannot be found on GitHub. It seems it was pushed directly referring to the original sled dependency.

**Comment by haxjump** [comment]
@prasannavl 
thanks much.
the sled project looks dead, let's use the rocksdb backend instead, which is also the default feature for the latest version
